# Generated by Django 5.2.14 on 2026-05-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dossier', models.CharField(max_length=20, unique=True, verbose_name='numéro de dossier médical')),
                ('antecedents', models.TextField(blank=True, verbose_name='antécédents')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'dossier patient',
                'verbose_name_plural': 'dossiers patients',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('tension', models.CharField(blank=True, max_length=20, verbose_name='tension')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='poids (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='température (°C)')),
                ('diagnostic', models.TextField(blank=True, verbose_name='diagnostic')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='compte rendu')),
                ('termine', models.BooleanField(default=False, verbose_name='terminé')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medecins.medecin', verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='patient')),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='rendez_vous.rendezvous', verbose_name='rendez-vous')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.dossierpatient', verbose_name='dossier')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('valide_jusqu', models.DateField(verbose_name="valide jusqu'au")),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'ordonnance',
                'verbose_name_plural': 'ordonnances',
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='médicament')),
                ('dosage', models.CharField(max_length=100, verbose_name='dosage')),
                ('duree', models.CharField(max_length=100, verbose_name='durée')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance', verbose_name='ordonnance')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
            },
        ),
    ]
