# Generated by Django 5.2.14 on 2026-05-14 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100, verbose_name='spécialité')),
                ('tarif_consultation', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='tarif consultation')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/', verbose_name='photo')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'médecin',
                'verbose_name_plural': 'médecins',
            },
        ),
    ]
