# Generated by Django 5.2.14 on 2026-05-14 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dossier', models.CharField(max_length=20, unique=True, verbose_name='numéro de dossier')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
    ]
